pr:
  - azure-pipelines
trigger:
  branches:
    include:
      - azure-pipelines
  paths:
    exclude:
      - '**/*.md'

jobs:
  - job: basic_linux
    displayName: 'linux'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: templates/basic-scenario.yml
        parameters:
          testCommand: 'yarn test'
          nodeVersion: '10'
          enableLinting: true

  - job: node_versions
    displayName: 'node'
    dependsOn: basic_linux
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        node_6:
          displayName: '6'
          nodeVer: '6.17'
        node_8:
          displayName: '8'
          nodeVer: '8'
        node_10:
          displayName: '10'
          nodeVer: '10'
        node_11:
          displayName: '11'
          nodeVer: '11'
    steps:
      - template: templates/basic-scenario.yml
        parameters:
          nodeVersion: $(nodeVer)

  - job: windows
    dependsOn: basic_linux
    displayName: 'windows 10'
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        node_6:
          displayName: '6'
          nodeVer: '6.17'
        node_8:
          displayName: '8'
          nodeVer: '8'
        node_10:
          displayName: '10'
          nodeVer: '10'

    steps:
      - template: templates/basic-scenario.yml
        parameters:
          nodeVersion: $(nodeVer)

  - job: other_tests
    displayName: 'scenario:'
    dependsOn: basic_linux
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        all_experiments:
          testCmdPrefix: 'EMBER_CLI_ENABLE_ALL_EXPERIMENTS=true'
        packager:
          testCmdPrefix: 'EMBER_CLI_PACKAGER=true'
        module_unification:
          testCmdPrefix: 'EMBER_CLI_MODULE_UNIFICATION=true'
        delayed_transpile:
          testCmdPrefix: 'EMBER_CLI_DELAYED_TRANSPILATION=true'
        no_system_temp:
          testCmdPrefix: 'EMBER_CLI_SYSTEM_TEMP=false'
    steps:
      - template: templates/basic-scenario.yml
        parameters:
          testCommandPrefix: $(testCmdPrefix)
